Repository OsamZo/hi-hello-vue, pull requests merged in 2024-12, with the labels that each got.

#4 [REFACTOR] 깃허브 Actions 코드 변경
  .github/workflows/deploy.yml
Labels: REFACTOR

#6 [FEAT] reset.css 추가
  src/assets/reset.css
Labels: FEAT

#13 [FEAT] vue 기본 설정 작업
  src/App.vue
  src/main.js
  vite.config.js
Labels: FEAT

#15 [FEAT] WhiteBox 컴포넌트 생성 작업
  src/components/WhiteBoxComponet.vue
Labels: FEAT

#16 [FEAT] 퀴즈 페이지 퍼블리싱 및 api 연동 작업
  src/api/axios.js
  src/components/WhiteBoxComponent.vue
  src/router/QuizRouter.js
  src/router/index.js
  src/services/QuizApi.js
  src/services/axios.js
  src/views/quiz/QuizPage.vue
  vite.config.js
Labels: FEAT

#19 [FEAT] reset.css 수정 및 main.js에 추가
  src/main.js
  src/styles/reset.css
Labels: FEAT

#20 [FEAT] Aside 컴포넌트 구현
  src/App.vue
  src/components/AsideComponent.vue
  src/styles/reset.css
Labels: FEAT

#21 [FEAT] 위키 등록 페이지 에디터 및 백엔드 연동
  package-lock.json
  package.json
  src/components/Tiptap.vue
  src/router/WikiRouter.js
  src/router/index.js
  src/services/WikiApi.js
  src/views/wiki/WikiCreatePage.vue
Labels: FEAT, DESIGN

#26 [REFACTOR] app 페이지 섹션 분리작업
  src/App.vue
Labels: REFACTOR, DESIGN

#28 [FEAT] LoginPage 퍼블리싱 작업
  package-lock.json
  package.json
  src/App.vue
  src/router/UserRouter.js
  src/router/index.js
  src/styles/user/LoginPage.css
  src/views/user/LoginPage.vue
Labels: FEAT, DESIGN

#30 [FEAT] user 로그인 관련 api연동 및 pinia 적용 작업
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/App.vue
  src/main.js
  src/router/MainRouter.js
  src/router/UserRouter.js
  src/router/index.js
  src/services/axios.js
  src/stores/UserStore.js
  src/views/MainPage.vue
  src/views/user/LoginPage.vue
Labels: FEAT, REFACTOR

#31 [FEAT] 위키 수정 에디터 및 백엔드 연동
  src/components/EditorComponent.vue
  src/router/WikiRouter.js
  src/services/WikiApi.js
  src/views/wiki/WikiCreatePage.vue
  src/views/wiki/WikiUpdatePage.vue
Labels: FEAT, RENAME

#35 [CHORE] 로그아웃 처리 로직 수정
  src/stores/UserStore.js
Labels: CHORE

#39 [FEAT] 리스트 컴포넌트 구현
  src/components/ListComponent.vue
  src/components/WhiteBoxListComponent.vue
  src/styles/reset.css
Labels: FEAT, DESIGN

#37 [CHORE] UserStore 설정 Security 설정과 맞도록 동기화
  src/stores/UserStore.js
Labels: CHORE

#43 [CHORE] UserStore 불필요한 설정 삭제
  src/stores/UserStore.js
Labels: CHORE

#44 [FEAT] 서치바 컴포넌트 구현
  src/assets/search-icon.png
  src/components/SearchBarComponent.vue
Labels: FEAT, DESIGN

#45 [FEAT] 인턴위키 리스트 조회 및 상세조회 페이지 구현
  src/App.vue
  src/components/AsideComponent.vue
  src/components/ListComponent.vue
  src/components/WhiteBoxListComponent.vue
  src/router/WikiRouter.js
  src/services/WikiApi.js
  src/views/wiki/WikiDetailReadPage.vue
  src/views/wiki/WikiListReadPage.vue
Labels: FEAT, DESIGN

#48 [FEAT] normalize.css 추가
  package-lock.json
  package.json
  src/main.js
  src/styles/reset.css
Labels: FEAT, REFACTOR

#50 [REFACTOR] 퀴즈 페이지 스타일 리펙토링 작업
  src/components/WhiteBoxComponent.vue
  src/styles/quiz/Quiz.css
  src/views/quiz/QuizPage.vue
Labels: REFACTOR

#55 [FEAT] 위키 히스토리 조회 모달 구현
  src/services/WikiApi.js
  src/views/wiki/WikiDetailReadPage.vue
  src/views/wiki/WikiHistoryModal.vue
  src/views/wiki/WikiUpdatePage.vue
Labels: FEAT, DESIGN

#57 [FEAT] jwt 토큰에서 사원 정보 추출 메서드 구현
  src/stores/UserStore.js
Labels: FEAT

#59 [FIX] jwt 토큰에서 사원 정보 추출 메서드 수정
  src/stores/UserStore.js
Labels: FIX

#61 [FEAT] 내 프로필 조회 컴포넌트 퍼블리싱 작업
  src/components/EmployeeProfile.vue
Labels: FEAT, DESIGN

#62 [FEAT] 과제 평가 결과 리스트 페이지 구현
  src/router/TaskEvalRouter.js
  src/router/index.js
  src/services/TaskEvalResultApi.js
  src/views/MainPage.vue
  src/views/task-eval/TaskEvalListResultReadPage.vue
  src/views/wiki/WikiListReadPage.vue
Labels: FEAT, DESIGN

#64 [DESIGN] 비밀번호 변경 컴포넌트 퍼블리싱
  src/components/EmployeeProfile.vue
  src/components/UpdatePassword.vue
Labels: CHORE, DESIGN

#66 [CHORE] 메인페이지 테스트용 코드 삭제
  src/views/MainPage.vue
Labels: CHORE

#68 [DESIGN] 사원 관리 페이지 퍼블리싱
  src/views/user/hr/EmployeeListPage.vue
Labels: DESIGN

#70 [DESIGN] 사원 등록 페이지 퍼블리싱
  src/views/user/hr/AddEmployeePage.vue
Labels: DESIGN

#71 [FEAT] 퀴즈 결과 페이지 api 연동 작업
  src/stores/QuizStore.js
  src/views/quiz/QuizPage.vue
  src/views/quiz/QuizResultPage.vue
Labels: FEAT

#76 [REFACTOR] 로그인 페이지 css 리펙토링
  src/styles/user/LoginPage.css
  src/views/user/LoginPage.vue
Labels: REFACTOR

#75 [DESIGN] 사원 정보 수정 확인 모달 퍼블리싱
  src/components/hr/employee/UpdateEmployeeModal.vue
  src/components/hr/employee/UpdatePassword.vue
Labels: RENAME, DESIGN

#86 [FEAT] 퀴즈 카테고리 컴포넌트 퍼블리싱 및 api 연동 작업
  src/components/QuizCategoryComponent.vue
  src/router/QuizRouter.js
  src/services/QuizApi.js
  src/views/quiz/HrQuizPage.vue
Labels: FEAT

#91 [FEAT] (담당자, 멘토) 과제 리스트 조회 페이지 구현
  src/assets/plus-icon.png
  src/components/AddTask.vue
  src/components/DeleteModalComponent.vue
  src/components/SearchBarComponent.vue
  src/components/UserRollRectangle.vue
  src/router/TaskRouter.js
  src/router/index.js
  src/services/TaskList.js
  src/styles/task/TaskListPage.css
  src/views/task/TaskAddPage.vue
  src/views/task/TaskListPage.vue
Labels: FEAT, DESIGN

#93 [FEAT] 담당자 퀴즈 조회 페이지 퍼블리싱 작업
  src/styles/quiz/HrQuiz.css
  src/views/quiz/HrQuizPage.vue
Labels: FEAT, DESIGN

#96 [CHORE] 로그아웃 시 로그인 화면으로 전환하도록 코드 추가
  src/stores/UserStore.js
Labels: CHORE

#97 [FEAT] 멘토 소개 페이지 퍼블리싱 작업
  src/components/AsideComponent.vue
  src/router/UserRouter.js
  src/views/user/MentorInfoPage.vue
Labels: FEAT, DESIGN

#100 [FEAT] 권한별 네비바 구현
  src/components/AsideComponent.vue
Labels: FEAT, DESIGN

#105 [FIX] logout 무한 호출 문제 해결
  src/stores/UserStore.js
  src/views/user/hr/modal/employee/DeleteEmployeeModal.vue
  src/views/user/hr/modal/employee/UpdateEmployeeModal.vue
  src/views/user/hr/modal/employee/UpdatePassword.vue
Labels: FIX, RENAME

#106 [FEAT] 멘토 프로필 조회 api 구현
  src/services/UserApi.js
  src/views/user/MentorInfoPage.vue
Labels: FEAT

#108 [FEAT] 멘토링 계획서 전체 조회, 검색 구현
  src/router/MentoringRouter.js
  src/services/MentoringApi.js
  src/styles/reset.css
  src/views/mentoring/MentoringPlaningListPage.vue
Labels: FEAT

#114 [FEAT] 담당자 퀴즈 조회 api 연동 작업
  src/router/QuizRouter.js
  src/services/QuizApi.js
  src/styles/quiz/HrQuiz.css
  src/views/quiz/HrQuizPage.vue
Labels: FEAT, REFACTOR

#118 [FEAT] 담당자 퀴즈 등록 기능 구현
  src/services/QuizApi.js
  src/views/quiz/AddQuizCategoryModal.vue
  src/views/quiz/AddQuizModal.vue
  src/views/quiz/HrQuizPage.vue
Labels: FEAT, RENAME, DESIGN

#122 [FEAT] (담당자, 멘토) 과제 등록 페이지 구현
  src/services/TaskAdd.js
  src/styles/task/TaskAddPage.css
  src/views/task/TaskAddPage.vue
Labels: FEAT, DESIGN

#123 [FEAT] (멘토) 멘토링 계획서 등록
  src/router/MentoringRouter.js
  src/services/MentoringApi.js
  src/styles/reset.css
  src/views/mentoring/MentoringPlanningCreate.vue
  src/views/mentoring/MentoringPlanningListPage.vue
Labels: FEAT, DESIGN

#127 [REFACTOR] endpoint 변경
  src/router/index.js
  src/services/MentoringApi.js
Labels: REFACTOR

#133 [FEAT] 멘토링 계획서 상세 조회
  src/router/MentoringRouter.js
  src/services/MentoringApi.js
  src/views/mentoring/MentoringPlanningCreatePage.vue
  src/views/mentoring/MentoringPlanningDetailPage.vue
  src/views/mentoring/MentoringPlanningListPage.vue
Labels: FEAT, DESIGN

#131 [CHORE] task기능 로직 수정
  src/services/TaskAdd.js
  src/services/TaskList.js
Labels: CHORE

#136 [FEAT] 담당자 퀴즈 수정 기능 구현
  src/services/QuizApi.js
  src/views/quiz/AddQuizModal.vue
  src/views/quiz/HrQuizPage.vue
  src/views/quiz/UpdateQuizModal.vue
Labels: FEAT, REFACTOR

#137 [FEAT] 담당자 퀴즈 삭제 기능 구현
  src/services/QuizApi.js
  src/views/quiz/HrQuizPage.vue
Labels: FEAT

#139 [REFACTOR] 로그인 스타일 리펙토링
  src/styles/user/LoginPage.css
  src/views/user/LoginPage.vue
Labels: REFACTOR, DESIGN

#141 [fix] 인터셉터 정상 작동하도록 수정
  src/stores/UserStore.js
Labels: FIX

#144 [FEAT] 퀴즈 카테고리 삭제 기능 구현
  src/components/QuizCategoryComponent.vue
  src/services/QuizCategoryApi.js
  src/views/quiz/HrQuizPage.vue
Labels: FEAT

#146 [REFACTOR] 관리자 퀴즈 관련 pinia 비활성화 작업
  src/components/QuizCategoryComponent.vue
  src/stores/QuizStore.js
  src/views/quiz/AddQuizCategoryModal.vue
  src/views/quiz/HrQuizPage.vue
  src/views/quiz/QuizPage.vue
  src/views/quiz/UpdateQuizModal.vue
Labels: REFACTOR

#149 [FEAT] 멘토 멘티 메칭 구현
  src/router/MentoringRouter.js
  src/services/MentoringApi.js
  src/views/mentoring/MentoringMatchingCreatePage.vue
Labels: FEAT, DESIGN

#147 [FEAT] 최종평가 리스트 조회 페이지 구현
  src/components/AsideComponent.vue
  src/components/SearchBarComponent.vue
  src/router/FinalEvalRouter.js
  src/router/index.js
  src/services/FinalEvalApi.js
  src/styles/final-eval/FinaleEvalListPage.css
  src/views/final-eval/FinalEvalListReadPage.vue
Labels: FEAT, DESIGN

#148 [CHORE] 아이콘 S3이미지로 변경
  src/assets/plus-icon.png
  src/assets/search-icon.png
  src/components/AddTask.vue
  src/components/SearchBarComponent.vue
Labels: CHORE

#152 [REFACTOR] 토큰 정보 추출을 위한 디코딩 과정 수정
  src/stores/UserStore.js
Labels: REFACTOR

#155 [CHORE] axios -> springAPI
  src/services/FinalEvalApi.js
  src/services/TaskEvalResultApi.js
  src/services/WikiApi.js
Labels: CHORE

#158 [FEAT] 최종 평가 상세 조회 페이지 구현
  src/router/FinalEvalRouter.js
  src/services/FinalEvalApi.js
  src/styles/final-eval/FinalEvalDetailPage.css
  src/styles/final-eval/FinalEvalListPage.css
  src/views/final-eval/FinalEvalDetailReadPage.vue
  src/views/final-eval/FinalEvalListReadPage.vue
  src/views/wiki/WikiListReadPage.vue
Labels: DESIGN

#161 [FEAT] 프로필 조회 api 및 비밀번호 변경 페이지로 라우팅
  src/App.vue
  src/components/AsideComponent.vue
  src/components/EmployeeProfile.vue
  src/router/UserRouter.js
  src/services/UserApi.js
  src/stores/UserStore.js
Labels: FEAT

#164 [FEAT] 담당자 퀴즈 결과 api 연동 작업
  src/services/QuizApi.js
  src/styles/quiz/QuizResult.css
  src/views/quiz/HrQuizResultPage.vue
Labels: FEAT

#165 [FEAT] 비밀번호 변경 페이지 api 연동
  src/App.vue
  src/components/EmployeeProfile.vue
  src/router/UserRouter.js
  src/services/UserApi.js
  src/views/user/UpdatePassword.vue
  src/views/user/hr/modal/employee/UpdatePassword.vue
Labels: FEAT

#166 [FEAT] 동료 평가 지표 관리 페이지 퍼블리싱 및 api 연동 작업
  src/router/PeerReviewRouter.js
  src/router/index.js
  src/services/PeerReviewApi.js
  src/styles/peer-review/PeerReviewList.css
  src/styles/quiz/HrQuizResult.css
  src/styles/reset.css
  src/views/peer-review/HrPeerReviewListPage.vue
  src/views/quiz/HrQuizResultPage.vue
Labels: FEAT, REFACTOR, DESIGN

#167 [FEAT] 동료 평가 조회 페이지 퍼블리싱
  src/router/PeerReviewRouter.js
  src/styles/peer-review/PeerReview.css
  src/views/peer-review/HrPeerReviewListPage.vue
  src/views/peer-review/HrPeerReviewPage.vue
Labels: FEAT, DESIGN

#169 [FEAT] 동료 평가 조회 api 연동 작업
  src/services/PeerReviewApi.js
  src/styles/peer-review/PeerReview.css
  src/views/peer-review/HrPeerReviewPage.vue
Labels: FEAT

#172 [REFACTOR] aside 구성 시 과도한 userStore 호출 로직 리팩토링
  src/components/AsideComponent.vue
  src/stores/UserStore.js
Labels: REFACTOR

#173 [FEAT] 온보딩 메인 페이지 구현
  src/services/OnBoarding.js
  src/styles/task/TaskListPage.css
  src/styles/user/MenteeOnboardingPage.css
  src/views/MainPage.vue
  src/views/task/TaskListPage.vue
Labels: FEAT, DESIGN

#174 [FEAT] 담당자 동료 평가 상세조회 기능 구현
  src/services/PeerReviewApi.js
  src/views/peer-review/HrPeerReviewDetailModal.vue
  src/views/peer-review/HrPeerReviewPage.vue
Labels: FEAT, DESIGN

#177 [REFACTOR] task 기능 css 코드 수정
  src/styles/task/TaskAddPage.css
  src/styles/task/TaskListPage.css
  src/views/task/TaskAddPage.vue
Labels: REFACTOR

#178 [CHORE] userStore 로그 및 주석 정리
  src/stores/UserStore.js
Labels: CHORE

#181 [REFACTOR] 파일 이동 및 사원 조회, 검색 api 연동
  src/router/UserRouter.js
  src/services/UserApi.js
  src/views/user/hr/AddEmployeePage.vue
  src/views/user/hr/EmployeeListPage.vue
  src/views/user/hr/views/employee/AddEmployeePage.vue
  src/views/user/hr/views/employee/EmployeeListPage.vue
Labels: FEAT

#183 [FEAT] mentee grouping 구현, 디자인
  src/router/TaskRouter.js
  src/services/GroupingApi.js
  src/services/TaskAdd.js
  src/views/task/GroupingPage.vue
  src/views/task/TaskAddPage.vue
Labels: FEAT, DESIGN

#185 [REFACTOR] 그룹핑 로직 수정
  src/router/TaskRouter.js
  src/services/GroupingApi.js
  src/styles/task/GroupingPage.css
  src/views/task/GroupingPage.vue
Labels: REFACTOR

#186 [FEAT] 평가 지표 관리 페이지 구현
  src/router/TaskIndRouter.js
  src/router/index.js
  src/services/taskIndManage.js
  src/styles/task-Ind/TaskIndManage.css
  src/views/task-ind/TaskIndManage.vue
Labels: FEAT, DESIGN

#188 [FEAT] (멘토) 과제 평가 페이지 구현
  src/components/AsideComponent.vue
  src/router/TaskRouter.js
  src/services/EvalListApi.js
  src/services/TaskApi.js
  src/services/TaskEvalApi.js
  src/styles/task/MentorTaskDetailReadPage.css
  src/views/task-eval/TaskEvalResultDetailReadModal.vue
  src/views/task-eval/TaskEvalResultListReadPage.vue
  src/views/task/MentorTaskDetailReadPage.vue
Labels: FEAT

#190 [FEAT] 담당자 챗봇 페이지 퍼블리싱
  src/router/ChatbotRouter.js
  src/router/index.js
  src/styles/chatbot/ChatbotCustom.css
  src/views/chatbot/AddChatbotCategoryModal.vue
  src/views/chatbot/AddChatbotModal.vue
  src/views/chatbot/ChatbotCategoryComponent.vue
  src/views/chatbot/HrChatbotCustomPage.vue
  src/views/chatbot/UpdateChatbotModal.vue
Labels: FEAT, DESIGN

#192 [FEAT] 동료 평가 화면 구현
  src/router/MainRouter.js
  src/router/PeerReviewRouter.js
  src/services/GroupEvalAPI.js
  src/services/OnBoardingAPI.js
  src/services/taskIndManage.js
  src/styles/peer-review/GroupEval.css
  src/views/onboarding/MainPage.vue
  src/views/peer-review/GroupEval.vue
Labels: FEAT, DESIGN

#194 [FEAT] 휴가 신청 페이지 퍼블리싱
  src/router/OnboardingRouter.js
  src/router/index.js
  src/styles/onboarding/BreakApply.css
  src/views/onboarding/BreakApplyPage.vue
Labels: FEAT, DESIGN

#197 [FEAT] 사원 삭제 모달 및 api 연동
  src/components/EmployeeProfile.vue
  src/services/UserApi.js
  src/views/user/UpdatePassword.vue
  src/views/user/hr/modal/employee/DeleteEmployeeModal.vue
  src/views/user/hr/modal/employee/UpdateEmployeeModal.vue
  src/views/user/hr/views/employee/EmployeeListPage.vue
Labels: FEAT

#199 [FEAT] 위키 에디터 CSS 구현
  package-lock.json
  package.json
  src/components/EditorComponent.vue
  src/main.js
  src/styles/task/GroupingPage.css
  src/styles/wiki/EditorComponent.css
  src/views/task/GroupingPage.vue
  src/views/task/MentorTaskDetailReadPage.vue
  src/views/wiki/WikiCreatePage.vue
  src/views/wiki/WikiDetailReadPage.vue
Labels: FEAT, DESIGN

#203 [FEAT] 사원 등록 페이지 구현 및 api 연동
  src/services/UserApi.js
  src/views/user/hr/views/employee/AddEmployeePage.vue
Labels: FEAT

#206 [FEAT] 퀴즈 카테고리 api 연동 작업
  src/services/ChatbotApi.js
  src/services/axios.js
  src/views/chatbot/AddChatbotCategoryModal.vue
  src/views/chatbot/ChatbotCategoryComponent.vue
  src/views/chatbot/HrChatbotCustomPage.vue
Labels: FEAT

#208 [FEAT] 사원 정보 수정 모달 구현 및 api 연동
  src/services/UserApi.js
  src/views/user/hr/modal/employee/UpdateEmployeeModal.vue
  src/views/user/hr/views/employee/EmployeeListPage.vue
Labels: FEAT

#209 [FEAT] 온보딩 설계 백엔드 연동
  src/router/OnboardingRouter.js
  src/services/OnboardingDataApi.js
  src/views/onboarding/OnboardingDataPage.vue
  src/views/task/GroupingPage.vue
Labels: FEAT

#211 [FEAT] 과제 상세 조회 페이지 버튼 백엔드 연동 및 특정 버전 위키 조회 구현
  src/router/WikiRouter.js
  src/services/WikiApi.js
  src/styles/task/GroupingPage.css
  src/styles/wiki/EditorComponent.css
  src/styles/wiki/WikiUpdatePage.css
  src/views/task/GroupingPage.vue
  src/views/wiki/WikiCreatePage.vue
  src/views/wiki/WikiDetailReadPage.vue
  src/views/wiki/WikiHistoryModal.vue
  src/views/wiki/WikiUpdatePage.vue
Labels: FEAT, CHORE

#212 [FEAT] 챗봇 데이터 api 연동 작업
  src/services/ChatbotApi.js
  src/views/chatbot/AddChatbotCategoryModal.vue
  src/views/chatbot/AddChatbotModal.vue
  src/views/chatbot/HrChatbotCustomPage.vue
  src/views/chatbot/UpdateChatbotModal.vue
Labels: FEAT, REFACTOR, DESIGN

#214 [FIX] 무한 호출 의심 코드 수정
  src/stores/UserStore.js
Labels: FIX

#216 [FIX] CSS 충돌
  src/components/EditorComponent.vue
  src/styles/wiki/EditorComponent.css
Labels: FIX

#218 [FEAT] 파일 다운로드 메서드 구현
  src/services/FileApi.js
  src/views/task/MentorTaskDetailReadPage.vue
Labels: FEAT

#219 [REFACTOR] Aside 코드 리펙토링 작업
  src/App.vue
  src/components/AsideComponent.vue
  src/services/OnboardingDataApi.js
  src/stores/UserStore.js
Labels: FEAT, REFACTOR

#221 [REFACTOR] 로그인 페이지 css 리펙토링
  src/styles/user/LoginPage.css
  src/views/user/LoginPage.vue
Labels: REFACTOR, DESIGN

#223 [REFACTOR] 과제 평가 상세 조회 모달 CSS 작업
  src/styles/task-eval/TaskEvalResultDetailReadModal.css
  src/views/task-eval/TaskEvalResultDetailReadModal.vue
  src/views/task-eval/TaskEvalResultListReadPage.vue
Labels: DESIGN

#225 [REFACTOR] CSS 리팩토링
  src/components/EditorComponent.vue
  src/styles/task/MentorTaskDetailReadPage.css
  src/views/task/MentorTaskDetailReadPage.vue
Labels: REFACTOR

#227 [DESIGN] 온보딩 퍼블리싱 완료
  src/services/OnboardingDataApi.js
  src/styles/onboarding/OnboardingData.css
  src/views/mentoring/MentoringPlanningCreatePage.vue
  src/views/onboarding/OnboardingDataPage.vue
Labels: FEAT, DESIGN

#228 [FEAT] 멘티 과제 제출 페이지 구현
  src/router/TaskRouter.js
  src/services/MenteeTaskDetailReadPage.js
  src/styles/task/MenteeTaskDetailReadPage.css
  src/views/task/MenteeTaskDetailReadPage.vue
Labels: FEAT, DESIGN

#230 [FEAT] 위키 목록 생성 기능 구현
  src/components/EditorComponent.vue
  src/views/wiki/WikiDetailReadPage.vue
Labels: FEAT

#232 [DESIGN] 아이콘 수정
  src/components/AddTask.vue
  src/components/SearchBarComponent.vue
  src/services/MenteeTaskDetailReadApi.js
  src/views/task/MenteeTaskDetailReadPage.vue
Labels: DESIGN

#234 [REFACTOR] role 권한 수정
  src/views/mentoring/MentoringPlanningListPage.vue
Labels: REFACTOR

#237 [FEAT] 멘토링 보고서 조회 화면 api 연동
  src/router/MentoringRouter.js
  src/services/MentoringApi.js
  src/views/mentoring/report/MentoringReportListPage.vue
Labels: FEAT

#239 [FEAT] 멘토링 보고서 작성 화면 api 연동
  src/router/MentoringRouter.js
  src/services/MentoringApi.js
  src/views/mentoring/report/MentoringCreateReportPage.vue
Labels: FEAT

#241 [FEAT] 멘토링 보고서 상세 조회 및 수정 api 연동
  src/components/AsideComponent.vue
  src/router/MentoringRouter.js
  src/services/MentoringApi.js
  src/views/mentoring/report/MentoringReportDetailPage.vue
  src/views/mentoring/report/MentoringReportListPage.vue
Labels: FEAT

#242 [REFACTOR] css 수정
  src/App.vue
  src/components/AsideComponent.vue
  src/components/EditorComponent.vue
  src/styles/final-eval/FinalEvalDetailPage.css
  src/styles/final-eval/FinalEvalListPage.css
  src/styles/onboarding/OnboardingData.css
  src/styles/peer-review/GroupEval.css
  src/styles/peer-review/PeerReview.css
  src/styles/peer-review/PeerReviewList.css
  src/styles/quiz/HrQuiz.css
  src/styles/quiz/HrQuizResult.css
  src/styles/task-Ind/TaskIndManage.css
  src/styles/task-eval/TaskEvalResultDetailReadModal.css
  src/styles/task/GroupingPage.css
  src/styles/task/MenteeTaskDetailReadPage.css
  src/styles/task/TaskAddPage.css
  src/styles/task/TaskListPage.css
  src/styles/wiki/EditorComponent.css
  src/views/final-eval/FinalEvalDetailReadPage.vue
  src/views/final-eval/FinalEvalListReadPage.vue
  src/views/onboarding/OnboardingDataPage.vue
  src/views/peer-review/HrPeerReviewDetailModal.vue
  src/views/peer-review/HrPeerReviewListPage.vue
  src/views/peer-review/HrPeerReviewPage.vue
  src/views/quiz/AddQuizCategoryModal.vue
  src/views/quiz/AddQuizModal.vue
  src/views/quiz/HrQuizPage.vue
  src/views/quiz/HrQuizResultPage.vue
  src/views/quiz/UpdateQuizModal.vue
  src/views/task-eval/TaskEvalResultDetailReadModal.vue
  src/views/task-eval/TaskEvalResultListReadPage.vue
  src/views/task/GroupingPage.vue
  src/views/task/TaskAddPage.vue
  src/views/task/TaskListPage.vue
  src/views/task/TaskModifyPage.vue
Labels: REFACTOR, DESIGN

#244 [FEAT] 멘토링 보고서 작성 시 sse를 이용한 실시간 알림 전송 구현
  package-lock.json
  package.json
  src/router/UserRouter.js
  src/router/index.js
  src/stores/UserStore.js
  src/stores/sse.js
Labels: FEAT, REFACTOR

#246 [REFACTOR] aside 모달 작동 이상: 이벤트 처리 리팩토링
  src/App.vue
  src/components/AsideComponent.vue
  src/components/EmployeeProfile.vue
  src/stores/sse.js
Labels: REFACTOR

#248 [FIX] userStore 리팩토링
  src/stores/UserStore.js
Labels: FIX, REFACTOR

#250 [FIX] 새로 고침 시 상태 초기화 증상 임시 조치
  src/components/AsideComponent.vue
  src/services/MentoringApi.js
Labels: FIX

#252 [FIX] 엑세스 토큰 만료 후 sse 재 연결 시 무한 호출 증상 조치
  src/stores/UserStore.js
Labels: FIX

#254 [FIX] 엑세스 토큰 만료 후 sse 재 연결 시 무한 루프 증상 조치 완료
  src/stores/UserStore.js
  src/stores/sse.js
Labels: FIX

#257 [REFACTOR] 온보딩 리스트 조회 로직 수정
  src/router/PeerReviewRouter.js
  src/router/TaskRouter.js
  src/services/OnBoardingAPI.js
  src/styles/onboarding/OnboardingData.css
  src/views/onboarding/MainPage.vue
  src/views/peer-review/GroupEval.vue
Labels: REFACTOR

#259 [FEAT] 위키 검색 관련 프론트 구현
  src/components/SearchBarComponent.vue
  src/services/WikiApi.js
  src/views/wiki/WikiListReadPage.vue
Labels: FEAT, DESIGN

#261 [FEAT] 알림창 퍼블리싱 및 api 연동
  src/components/AlarmModal.vue
  src/components/AsideComponent.vue
  src/services/AlramApi.js
  src/stores/UserStore.js
  src/views/mentoring/report/MentoringReportDetailPage.vue
Labels: FEAT

#265 [CHORE] task css 수정
  src/App.vue
  src/components/AddTask.vue
  src/components/DeleteModalComponent.vue
  src/components/UserRollRectangle.vue
  src/services/MenteeTaskDetailReadApi.js
  src/services/TaskAddApi.js
  src/services/TaskListApi.js
  src/services/TaskModifyApi.js
  src/styles/peer-review/GroupEval.css
  src/styles/task-Ind/TaskIndManage.css
  src/styles/task/MenteeTaskDetailReadPage.css
  src/styles/task/TaskAddPage.css
  src/styles/task/TaskListPage.css
  src/styles/task/TaskModifyPage.css
  src/views/task/TaskAddPage.vue
  src/views/task/TaskListPage.vue
  src/views/task/TaskModifyPage.vue
Labels: CHORE

#264 [FEAT] 온보딩 메인 화면 구현
  src/App.vue
  src/styles/onboarding/OnboardingData.css
  src/styles/user/MenteeOnboardingPage.css
  src/views/onboarding/MainPage.vue
Labels: FEAT, DESIGN

#267 [REFACTOR] 알림창 디테일 작업
  src/App.vue
  src/components/AsideComponent.vue
  src/stores/sse.js
Labels: REFACTOR

#270 [REFACTOR] 계획서 처리 로직 리팩토링
  src/services/MentoringApi.js
  src/views/mentoring/MentoringPlanningDetailPage.vue
Labels: REFACTOR

#271 [CHORE] task css 수정 2차
  src/App.vue
  src/services/TaskAddApi.js
  src/services/TaskModifyApi.js
  src/styles/task-Ind/TaskIndManage.css
  src/styles/task/MenteeTaskDetailReadPage.css
  src/styles/task/TaskAddPage.css
  src/styles/task/TaskModifyPage.css
  src/views/task/TaskAddPage.vue
  src/views/task/TaskModifyPage.vue
Labels: CHORE

#273 [FEAT] 온보딩 메인 페이지 모달 디자인
  src/App.vue
  src/styles/onboarding/OnboardingData.css
  src/styles/user/MenteeOnboardingPage.css
Labels: FEAT, DESIGN

#274 [FEAT] 채팅 연동
  package-lock.json
  package.json
  src/App.vue
  src/components/ChatModal.vue
  src/router/ChatRouter.js
  src/router/index.js
  src/services/ChatApi.js
  src/stores/ChatStore.js
  src/stores/WebSocketStore.js
  src/views/chat/Chatting.vue
  vite.config.js
Labels: FEAT

#277 [FEAT] 온보딩 박스 기본 위치 지정
  src/styles/user/MenteeOnboardingPage.css
  src/views/onboarding/MainPage.vue
Labels: FEAT, DESIGN

#280 [REFACTOR] sse 연결 로직 리팩토링
  src/stores/sse.js
Labels: REFACTOR

#282 [FEAT] 회의실 예약 기능 구현
  package-lock.json
  package.json
  src/router/OnboardingRouter.js
  src/styles/onboarding/OnboardingConferenceRoom.css
  src/styles/reset.css
  src/styles/task-Ind/TaskIndManage.css
  src/views/onboarding/ConferenceRoomPage.vue
Labels: FEAT, DESIGN

#283 [REFACTOR] 과제 평가 페이지 CSS 수정
  src/styles/final-eval/FinalEvalListPage.css
  src/styles/task/MentorTaskDetailReadPage.css
  src/styles/task/TaskAddPage.css
  src/styles/user/MenteeOnboardingPage.css
  src/views/task/MentorTaskDetailReadPage.vue
Labels: REFACTOR

#288 [REFACTOR] 온보딩 관련 기능 구현 및 리팩토링
  src/components/AsideComponent.vue
  src/services/OnBoardingAPI.js
  src/styles/reset.css
  src/styles/user/MenteeOnboardingPage.css
  src/views/onboarding/MainPage.vue
Labels: FEAT, REFACTOR, DESIGN

#290 [REFACTOR] Onboarding 템플릿 리팩토링 2차
  package-lock.json
  src/services/OnBoardingAPI.js
  src/styles/user/MenteeOnboardingPage.css
  src/views/onboarding/BreakApplyPage.vue
  src/views/onboarding/ConferenceRoomPage.vue
  src/views/onboarding/MainPage.vue
Labels: REFACTOR

#292 [REFACTOR] taskList -> Modify 연결
  src/views/task/TaskListPage.vue
Labels: CHORE

#296 [REFACTOR] 메뉴바 과제 관리 수정
  src/components/AsideComponent.vue
Labels: CHORE

#299 [FEAT] 그룹 멤버 조회 모달 구현
  src/services/GroupingApi.js
  src/styles/task-eval/TaskEvalResultDetailReadModal.css
  src/views/task-eval/TaskEvalResultDetailReadModal.vue
  src/views/task-eval/TaskEvalResultGroupMembersReadModal.vue
Labels: FEAT, DESIGN

#301 [FIX] 온보딩 메인페이지 멘토 수행 완료 에러 해결
  src/services/OnBoardingAPI.js
  src/views/onboarding/MainPage.vue
Labels: FIX

#303 [DESIGN] 멘토링 채팅 디자인
  src/components/ChatModal.vue
  src/services/ChatApi.js
  src/views/chat/Chatting.vue
Labels: DESIGN

#304 [REFACTOR] 메인화면 리팩토링 3차
  src/services/OnBoardingAPI.js
  src/styles/user/MenteeOnboardingPage.css
  src/views/onboarding/MainPage.vue
Labels: REFACTOR

#306 [FEAT] 체크리스트 모두 체크 시 온보딩 수행 완료되도록 구현
  src/services/OnBoardingAPI.js
  src/views/onboarding/MainPage.vue
Labels: FEAT

#308 [CHORE] 회의실 예약 css 간섭 해결
  src/styles/onboarding/OnboardingConferenceRoom.css
  src/views/onboarding/ConferenceRoomPage.vue
Labels: CHORE

#310 [CHORE] 과제 수정 로직 수정
  src/App.vue
  src/components/ChatBotModal.vue
  src/services/TaskModifyApi.js
  src/views/onboarding/MainPage.vue
  src/views/task/TaskModifyPage.vue
Labels: CHORE

#312 [CHORE] 퀴즈 라우팅 수정
  src/router/QuizRouter.js
  src/styles/user/MenteeOnboardingPage.css
  src/views/onboarding/MainPage.vue
Labels: CHORE

#314 [FEAT] 채팅 리스트 조회
  src/App.vue
  src/components/ChatModal.vue
  src/services/ChatApi.js
  src/views/chat/Chatting.vue
Labels: FEAT, DESIGN

#317 [FIX] 체크리스트 및 에디터 관련 오류 해결
  src/components/EditorComponent.vue
  src/services/OnBoardingAPI.js
  src/styles/reset.css
  src/views/onboarding/MainPage.vue
Labels: FIX

#319 [CHORE] 사원 관리 페이지 CSS 수정
  src/views/user/hr/modal/employee/DeleteEmployeeModal.vue
  src/views/user/hr/modal/employee/UpdateEmployeeModal.vue
  src/views/user/hr/views/employee/EmployeeListPage.vue
Labels: CHORE

#321 [CHORE] 보고서 관련 페이지 및 알람 모달 css 수정
  src/components/AlarmModal.vue
  src/components/AsideComponent.vue
  src/views/mentoring/report/MentoringCreateReportPage.vue
  src/views/mentoring/report/MentoringReportDetailPage.vue
  src/views/mentoring/report/MentoringReportListPage.vue
Labels: CHORE

#323 [FEAT] 로컬 스토리지에 boxPosition 빈 배열로 들어있을 때 초기화 로직 수정
  src/styles/user/MenteeOnboardingPage.css
  src/views/onboarding/MainPage.vue
Labels: REFACTOR

#325 [REFACTOR] aside 수정
  src/components/AsideComponent.vue
Labels: REFACTOR

#327 [REFACTOR] 위키 관련 개선점 리팩토링
  src/views/wiki/WikiCreatePage.vue
  src/views/wiki/WikiDetailReadPage.vue
  src/views/wiki/WikiHistoryModal.vue
  src/views/wiki/WikiUpdatePage.vue
Labels: REFACTOR, CHORE, DESIGN

#330 [REFACTOR] 멘토링 보고서 관련 수정
  src/views/mentoring/MentoringPlanningCreatePage.vue
  src/views/mentoring/MentoringPlanningDetailPage.vue
  src/views/mentoring/MentoringPlanningListPage.vue
Labels: REFACTOR

#333 [REFACTOR] 온보딩 설계 수정
  src/services/OnboardingDataApi.js
  src/styles/onboarding/OnboardingData.css
  src/views/onboarding/OnboardingDataPage.vue
Labels: REFACTOR

#334 [CHORE] 알림, 사원 관련 css 디테일 수정
  src/components/AlarmModal.vue
  src/components/AsideComponent.vue
  src/views/user/hr/views/employee/EmployeeListPage.vue
Labels: CHORE

#335 [REFACTOR] 과제 전체 수정
  src/components/AddTask.vue
  src/components/DeleteModalComponent.vue
  src/services/TaskAddApi.js
  src/services/TaskModifyApi.js
  src/styles/onboarding/OnboardingConferenceRoom.css
  src/styles/reset.css
  src/styles/task/TaskAddPage.css
  src/styles/task/TaskListPage.css
  src/styles/task/TaskModifyPage.css
  src/views/task/TaskAddPage.vue
  src/views/task/TaskModifyPage.vue
Labels: REFACTOR

#338 [CHORE] 사원, 멘토링 보고서 관련 페이지 버튼 통일 및 css 디테일 수정
  src/components/ListComponent.vue
  src/views/mentoring/report/MentoringCreateReportPage.vue
  src/views/mentoring/report/MentoringReportDetailPage.vue
  src/views/mentoring/report/MentoringReportListPage.vue
  src/views/user/hr/views/employee/AddEmployeePage.vue
  src/views/user/hr/views/employee/EmployeeListPage.vue
Labels: CHORE

#341 [CHORE] 평가지표 CSS 수정
  src/styles/task-Ind/TaskIndManage.css
Labels: CHORE
