Repository OsamZo/hi-hello-vue, pull requests merged in 2025-01, with the labels that each got.

#343 [REFACTOR] 요청 설정 코드 추가
  src/components/AsideComponent.vue
Labels: REFACTOR

#345 [REFACTOR] 퀴즈 api 호출 리펙토링
  src/router/QuizRouter.js
  src/views/quiz/QuizPage.vue
  src/views/quiz/QuizResultPage.vue
Labels: REFACTOR

#347 [REFACOTR] 온보딩 설계 체크리스트 수정
  src/styles/onboarding/OnboardingData.css
  src/views/onboarding/OnboardingDataPage.vue
Labels: REFACTOR

#348 [FEAT] 배포 1차
  src/components/AddTask.vue
  src/components/AlarmModal.vue
  src/components/AsideComponent.vue
  src/components/DeleteModalComponent.vue
  src/components/ListComponent.vue
  src/router/QuizRouter.js
  src/services/OnboardingDataApi.js
  src/services/TaskAddApi.js
  src/services/TaskApi.js
  src/services/TaskModifyApi.js
  src/styles/onboarding/OnboardingConferenceRoom.css
  src/styles/onboarding/OnboardingData.css
  src/styles/reset.css
  src/styles/task-Ind/TaskIndManage.css
  src/styles/task/MentorTaskDetailReadPage.css
  src/styles/task/TaskAddPage.css
  src/styles/task/TaskListPage.css
  src/styles/task/TaskModifyPage.css
  src/styles/user/MenteeOnboardingPage.css
  src/views/mentoring/MentoringPlanningCreatePage.vue
  src/views/mentoring/MentoringPlanningDetailPage.vue
  src/views/mentoring/MentoringPlanningListPage.vue
  src/views/mentoring/report/MentoringCreateReportPage.vue
  src/views/mentoring/report/MentoringReportDetailPage.vue
  src/views/mentoring/report/MentoringReportListPage.vue
  src/views/onboarding/MainPage.vue
  src/views/onboarding/OnboardingDataPage.vue
  src/views/quiz/QuizPage.vue
  src/views/quiz/QuizResultPage.vue
  src/views/task/MentorTaskDetailReadPage.vue
  src/views/task/TaskAddPage.vue
  src/views/task/TaskModifyPage.vue
  src/views/user/hr/modal/employee/DeleteEmployeeModal.vue
  src/views/user/hr/modal/employee/UpdateEmployeeModal.vue
  src/views/user/hr/views/employee/AddEmployeePage.vue
  src/views/user/hr/views/employee/EmployeeListPage.vue
  src/views/wiki/WikiCreatePage.vue
  src/views/wiki/WikiDetailReadPage.vue
  src/views/wiki/WikiHistoryModal.vue
  src/views/wiki/WikiUpdatePage.vue
Labels: FEAT

#350 [REFACTOR] 온보딩 설계 디자인 수정
  src/styles/onboarding/OnboardingData.css
Labels: REFACTOR

#352 [CHORE] 버튼 색상 변경 task-add
  src/styles/task/TaskAddPage.css
Labels: CHORE

#359 [REFACTOR] 전체 css 수정
  src/components/AsideComponent.vue
  src/components/ListComponent.vue
  src/components/SearchBarComponent.vue
  src/styles/final-eval/FinalEvalDetailPage.css
  src/styles/final-eval/FinalEvalListPage.css
  src/styles/peer-review/PeerReview.css
  src/styles/peer-review/PeerReviewList.css
  src/styles/quiz/HrQuizResult.css
  src/styles/task-Ind/TaskIndManage.css
  src/styles/task-eval/TaskEvalResultDetailReadModal.css
  src/styles/task/GroupingPage.css
  src/styles/task/MentorTaskDetailReadPage.css
  src/styles/task/TaskAddPage.css
  src/styles/task/TaskListPage.css
  src/styles/task/TaskModifyPage.css
  src/styles/user/MenteeInfoPage.css
  src/styles/user/MenteeOnboardingPage.css
  src/styles/user/MentorInfoPage.css
  src/styles/wiki/WikiUpdatePage.css
  src/views/chat/Chatting.vue
  src/views/mentoring/MentoringMatchingCreatePage.vue
  src/views/mentoring/MentoringPlanningCreatePage.vue
  src/views/mentoring/MentoringPlanningDetailPage.vue
  src/views/mentoring/MentoringPlanningListPage.vue
  src/views/mentoring/report/MentoringReportListPage.vue
  src/views/task-eval/TaskEvalResultGroupMembersReadModal.vue
  src/views/task-eval/TaskEvalResultListReadPage.vue
  src/views/user/MenteeInfoPage.vue
  src/views/user/MentorInfoPage.vue
  src/views/user/hr/views/employee/EmployeeListPage.vue
  src/views/wiki/WikiCreatePage.vue
  src/views/wiki/WikiHistoryModal.vue
  src/views/wiki/WikiListReadPage.vue
Labels: REFACTOR

#360 [FEAT] 위키 뒤로가기 버튼 생성
  src/views/wiki/WikiCreatePage.vue
  src/views/wiki/WikiDetailReadPage.vue
Labels: FEAT

#355 [REFACTOR] 버튼 색상 변경 및 그룹과제일 경우에만 그룹 조회 가능하도록 리팩토링
  src/components/EditorComponent.vue
  src/styles/final-eval/FinalEvalDetailPage.css
  src/styles/final-eval/FinalEvalListPage.css
  src/styles/onboarding/OnboardingData.css
  src/styles/task/MentorTaskDetailReadPage.css
  src/views/final-eval/FinalEvalDetailReadPage.vue
  src/views/final-eval/FinalEvalListReadPage.vue
  src/views/task-eval/TaskEvalResultDetailReadModal.vue
  src/views/task-eval/TaskEvalResultListReadPage.vue
  src/views/wiki/WikiDetailReadPage.vue
  src/views/wiki/WikiHistoryModal.vue
  src/views/wiki/WikiListReadPage.vue
Labels: REFACTOR, DESIGN

#361 [FEAT] 배포 환경 테스트 2
  src/components/AsideComponent.vue
  src/components/EditorComponent.vue
  src/components/ListComponent.vue
  src/components/SearchBarComponent.vue
  src/styles/final-eval/FinalEvalDetailPage.css
  src/styles/final-eval/FinalEvalListPage.css
  src/styles/onboarding/OnboardingData.css
  src/styles/peer-review/PeerReview.css
  src/styles/peer-review/PeerReviewList.css
  src/styles/quiz/HrQuizResult.css
  src/styles/task-Ind/TaskIndManage.css
  src/styles/task-eval/TaskEvalResultDetailReadModal.css
  src/styles/task/GroupingPage.css
  src/styles/task/MentorTaskDetailReadPage.css
  src/styles/task/TaskAddPage.css
  src/styles/task/TaskListPage.css
  src/styles/task/TaskModifyPage.css
  src/styles/user/MenteeInfoPage.css
  src/styles/user/MenteeOnboardingPage.css
  src/styles/user/MentorInfoPage.css
  src/styles/wiki/WikiUpdatePage.css
  src/views/chat/Chatting.vue
  src/views/final-eval/FinalEvalDetailReadPage.vue
  src/views/final-eval/FinalEvalListReadPage.vue
  src/views/mentoring/MentoringMatchingCreatePage.vue
  src/views/mentoring/MentoringPlanningCreatePage.vue
  src/views/mentoring/MentoringPlanningDetailPage.vue
  src/views/mentoring/MentoringPlanningListPage.vue
  src/views/mentoring/report/MentoringReportListPage.vue
  src/views/task-eval/TaskEvalResultDetailReadModal.vue
  src/views/task-eval/TaskEvalResultGroupMembersReadModal.vue
  src/views/task-eval/TaskEvalResultListReadPage.vue
  src/views/user/MenteeInfoPage.vue
  src/views/user/MentorInfoPage.vue
  src/views/user/hr/views/employee/EmployeeListPage.vue
  src/views/wiki/WikiCreatePage.vue
  src/views/wiki/WikiDetailReadPage.vue
  src/views/wiki/WikiHistoryModal.vue
  src/views/wiki/WikiListReadPage.vue
Labels: FEAT

#363 [CHORE] 온보딩 설계, aside 수정
  src/components/AsideComponent.vue
  src/services/OnboardingDataApi.js
  src/views/onboarding/OnboardingDataPage.vue
Labels: CHORE

#368 [REFACTOR] 온보딩 메인 화면 리팩토링
  src/components/AsideComponent.vue
  src/styles/user/MenteeOnboardingPage.css
  src/views/onboarding/MainPage.vue
Labels: REFACTOR

#370 [REFACTOR] 채팅 관련 수정
  src/components/ChatModal.vue
  src/services/GroupingApi.js
  src/views/chat/Chatting.vue
Labels: REFACTOR

#373 [REFACTOR] deploy 수정
  .github/workflows/deploy.yml
Labels: REFACTOR

#372 [FEAT] 배포 환경 테스트 3
  .github/workflows/deploy.yml
  src/components/AsideComponent.vue
  src/components/ChatModal.vue
  src/services/GroupingApi.js
  src/services/OnboardingDataApi.js
  src/services/TaskAddApi.js
  src/styles/user/MenteeOnboardingPage.css
  src/views/chat/Chatting.vue
  src/views/onboarding/MainPage.vue
  src/views/onboarding/OnboardingDataPage.vue
  src/views/task/GroupingPage.vue
  src/views/task/TaskAddPage.vue
Labels: FEAT

#375 [FEAT] 권한별 로그인 후 라우팅 처리
  src/router/index.js
  src/views/user/LoginPage.vue
Labels: FEAT

#378 [REFACTOR] 웹브라우저 종료 시 로컬 스토리지 내의 토큰 제거
  src/App.vue
Labels: REFACTOR

#379 [FIX] 온보딩 템플릿 드래그 시 위치 오류 해결
  src/styles/user/MenteeOnboardingPage.css
  src/views/onboarding/MainPage.vue
Labels: FIX, DESIGN

#381 [TEST] 배포 테스트
  .github/workflows/deploy.yml
Labels: TEST

#383 [REFACTOR] Aside 리팩토링
  src/components/AsideComponent.vue
Labels: REFACTOR

#385 [CHORE] url 수정
  src/App.vue
Labels: CHORE

#387 [FIX] 앱 언마운트시 토큰 제거 로직 삭제
  src/App.vue
Labels: FIX

#389 [FIX] 체크리스트-온보딩 수행 상태 변경 에러 해결
  src/services/OnBoardingAPI.js
  src/styles/wiki/EditorComponent.css
  src/views/onboarding/MainPage.vue
Labels: FIX, DESIGN

#391 [CHORE] 보고서 상세 조회 화면 뒤로가기 버튼 추가
  src/views/mentoring/report/MentoringReportDetailPage.vue
  src/views/user/hr/modal/employee/DeleteEmployeeModal.vue
Labels: CHORE

#393 [REFACTOR] 과제 등록 로직 수정
  src/services/OnboardingDataApi.js
  src/services/TaskAddApi.js
  src/views/chat/Chatting.vue
  src/views/onboarding/OnboardingDataPage.vue
  src/views/task/GroupingPage.vue
Labels: REFACTOR

#395 [REFACTOR] CSS 디테일 수정
  src/styles/final-eval/FinalEvalDetailPage.css
  src/styles/peer-review/PeerReviewList.css
  src/styles/task-Ind/TaskIndManage.css
  src/styles/task/MentorTaskDetailReadPage.css
  src/views/final-eval/FinalEvalDetailReadPage.vue
  src/views/final-eval/FinalEvalListReadPage.vue
  src/views/task/MentorTaskDetailReadPage.vue
  src/views/wiki/WikiHistoryModal.vue
Labels: REFACTOR, DESIGN

#397 [FIX] 오류 로직, CSS 수정
  src/components/EmployeeProfile.vue
  src/services/FileApi.js
  src/services/MenteeTaskDetailReadApi.js
  src/styles/peer-review/PeerReviewList.css
  src/styles/task-Ind/TaskIndManage.css
  src/styles/task-eval/TaskEvalResultDetailReadModal.css
  src/styles/task/TaskAddPage.css
  src/styles/task/TaskListPage.css
  src/styles/user/MenteeOnboardingPage.css
  src/views/onboarding/MainPage.vue
  src/views/peer-review/HrPeerReviewListPage.vue
  src/views/task-ind/TaskIndManage.vue
  src/views/task/MenteeTaskDetailReadPage.vue
  src/views/task/MentorTaskDetailReadPage.vue
  src/views/task/TaskAddPage.vue
  src/views/task/TaskListPage.vue
Labels: FIX

#399 [FEAT] 읽지 않은 알림 개수 조회 api 연동 및 퍼블리싱
  src/components/AlarmModal.vue
  src/components/AsideComponent.vue
  src/services/AlramApi.js
  src/stores/NotificationStore.js
  src/views/user/hr/views/employee/EmployeeListPage.vue
Labels: FEAT, CHORE

#401 [REFACTOR] 최종평가 프론트 리팩토링
  src/components/AsideComponent.vue
  src/services/FinalEvalApi.js
  src/views/final-eval/FinalEvalListReadPage.vue
Labels: REFACTOR

#403 [REFACTOR] security 관련 리팩토링
  src/App.vue
  src/components/AsideComponent.vue
  src/stores/UserStore.js
  src/stores/sse.js
Labels: REFACTOR

#404 [REFACTOR] 온보딩 설계 리팩토링
  src/services/OnboardingDataApi.js
  src/views/onboarding/OnboardingDataPage.vue
Labels: REFACTOR

#405 [REFACTOR] 퀴즈 카테고리 연동
  src/services/OnboardingDataApi.js
  src/views/mentoring/MentoringMatchingCreatePage.vue
  src/views/onboarding/OnboardingDataPage.vue
Labels: REFACTOR

#407 [REFACTOR] (담당자 로그인 시) 로그 삭제 및 디테일 수정
  src/App.vue
  src/components/AlarmModal.vue
  src/components/AsideComponent.vue
  src/main.js
  src/router/index.js
  src/services/OnboardingDataApi.js
  src/views/final-eval/FinalEvalDetailReadPage.vue
  src/views/mentoring/MentoringMatchingCreatePage.vue
  src/views/mentoring/MentoringPlanningDetailPage.vue
  src/views/mentoring/MentoringPlanningListPage.vue
  src/views/mentoring/report/MentoringReportListPage.vue
  src/views/onboarding/OnboardingDataPage.vue
  src/views/task-eval/TaskEvalResultListReadPage.vue
  src/views/user/LoginPage.vue
  src/views/user/hr/views/employee/EmployeeListPage.vue
Labels: REFACTOR

#414 [REFACTOR] 엘라스틱 서치 인덱스 생성
  src/App.vue
  src/services/WikiApi.js
  src/styles/task-eval/TaskEvalResultDetailReadModal.css
  src/views/final-eval/FinalEvalDetailReadPage.vue
  src/views/task-eval/TaskEvalResultListReadPage.vue
  src/views/wiki/WikiCreatePage.vue
  src/views/wiki/WikiListReadPage.vue
Labels: REFACTOR

#411 [FIX] 과제 제출 로직 수정
  src/services/TaskAddApi.js
  src/views/task/TaskAddPage.vue
Labels: FIX

#380 [FEAT] 배포 환경 테스트 4
  .github/workflows/deploy.yml
  src/App.vue
  src/components/AlarmModal.vue
  src/components/AsideComponent.vue
  src/components/EmployeeProfile.vue
  src/main.js
  src/router/index.js
  src/services/AlramApi.js
  src/services/FileApi.js
  src/services/FinalEvalApi.js
  src/services/MenteeTaskDetailReadApi.js
  src/services/OnBoardingAPI.js
  src/services/OnboardingDataApi.js
  src/services/TaskAddApi.js
  src/services/WikiApi.js
  src/stores/NotificationStore.js
  src/stores/UserStore.js
  src/stores/sse.js
  src/styles/final-eval/FinalEvalDetailPage.css
  src/styles/peer-review/PeerReviewList.css
  src/styles/task-Ind/TaskIndManage.css
  src/styles/task-eval/TaskEvalResultDetailReadModal.css
  src/styles/task/MentorTaskDetailReadPage.css
  src/styles/task/TaskAddPage.css
  src/styles/task/TaskListPage.css
  src/styles/user/MenteeOnboardingPage.css
  src/styles/wiki/EditorComponent.css
  src/views/chat/Chatting.vue
  src/views/final-eval/FinalEvalDetailReadPage.vue
  src/views/final-eval/FinalEvalListReadPage.vue
  src/views/mentoring/MentoringMatchingCreatePage.vue
  src/views/mentoring/MentoringPlanningDetailPage.vue
  src/views/mentoring/MentoringPlanningListPage.vue
  src/views/mentoring/report/MentoringReportDetailPage.vue
  src/views/mentoring/report/MentoringReportListPage.vue
  src/views/onboarding/MainPage.vue
  src/views/onboarding/OnboardingDataPage.vue
  src/views/peer-review/HrPeerReviewListPage.vue
  src/views/task-eval/TaskEvalResultListReadPage.vue
  src/views/task-ind/TaskIndManage.vue
  src/views/task/GroupingPage.vue
  src/views/task/MenteeTaskDetailReadPage.vue
  src/views/task/MentorTaskDetailReadPage.vue
  src/views/task/TaskAddPage.vue
  src/views/task/TaskListPage.vue
  src/views/user/LoginPage.vue
  src/views/user/hr/modal/employee/DeleteEmployeeModal.vue
  src/views/user/hr/views/employee/EmployeeListPage.vue
  src/views/wiki/WikiCreatePage.vue
  src/views/wiki/WikiHistoryModal.vue
  src/views/wiki/WikiListReadPage.vue
Labels: FEAT

#409 [CHORE] 담당자 로그인 시 화면 CSS 수정 및 로그 삭제
  src/styles/final-eval/FinalEvalDetailPage.css
  src/styles/final-eval/FinalEvalListPage.css
  src/styles/task-Ind/TaskIndManage.css
  src/views/task-eval/TaskEvalResultListReadPage.vue
  src/views/wiki/WikiListReadPage.vue
Labels: CHORE

#416 [FIX] 무한 리다이렉트 수정
  src/router/index.js
  src/views/user/LoginPage.vue
Labels: FIX

#419 [REFACTOR] 팀장 로그인 시 멘토링 메뉴 중복 노출 수정
  src/components/AsideComponent.vue
  src/router/index.js
Labels: REFACTOR

#421 [CHORE] 팀장, 멘토, 멘티 로그인 시 css, 디테일 수정
  src/components/AsideComponent.vue
  src/components/EmployeeProfile.vue
  src/views/mentoring/MentoringPlanningCreatePage.vue
  src/views/mentoring/report/MentoringReportDetailPage.vue
Labels: CHORE

#423 [REFACTOR] 담당자 퀴즈, 챗봇 커스텀 css 리펙토링
  src/styles/chatbot/ChatbotCustom.css
  src/styles/quiz/HrQuiz.css
Labels: REFACTOR

#424 [FIX] task 기능 수정
  src/components/AsideComponent.vue
  src/services/TaskAddApi.js
  src/services/TaskListApi.js
  src/views/mentoring/MentoringMatchingCreatePage.vue
Labels: FIX

#426 [FIX] 공통 과제 매칭
  src/services/GroupingApi.js
  src/views/task/GroupingPage.vue
Labels: FIX

#428 [CHORE] log 주석처리
  src/App.vue
  src/services/ChatApi.js
  src/services/MenteeTaskDetailReadApi.js
  src/services/MentoringApi.js
  src/services/OnBoardingAPI.js
  src/services/TaskIndManageApi.js
  src/services/TaskListApi.js
  src/services/UserApi.js
  src/services/WikiApi.js
  src/stores/WebSocketStore.js
  src/views/chat/Chatting.vue
  src/views/mentoring/MentoringPlanningCreatePage.vue
  src/views/mentoring/MentoringPlanningListPage.vue
  src/views/mentoring/report/MentoringReportDetailPage.vue
  src/views/onboarding/ConferenceRoomPage.vue
  src/views/onboarding/MainPage.vue
  src/views/quiz/QuizPage.vue
  src/views/task-eval/TaskEvalResultGroupMembersReadModal.vue
  src/views/task/GroupingPage.vue
  src/views/user/UpdatePassword.vue
Labels: CHORE

#431 [REFACTOR] aside 리팩토링
  src/components/AsideComponent.vue
  src/stores/UserStore.js
  src/views/user/MenteeInfoPage.vue
Labels: REFACTOR

#433 [REFACTOR] 수정사항
  src/styles/onboarding/OnboardingData.css
  src/styles/user/MenteeOnboardingPage.css
  src/views/chat/Chatting.vue
  src/views/wiki/WikiDetailReadPage.vue
Labels: REFACTOR

#434 배포
  src/styles/onboarding/OnboardingData.css
  src/styles/user/MenteeOnboardingPage.css
  src/views/chat/Chatting.vue
  src/views/wiki/WikiDetailReadPage.vue
Labels: FEAT
